name: Docker CiCd cho Advanced Forum
on :
  push :
    branches: [ "main", "master" ]
  pull_request :
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Kéo mã nguồn
        uses: actions/checkout@v4

      - name: kiểm tra phiên bản Docker
        run: |
          docker --version
          docker-compose --version

      - name: Chạy cac container
        run: docker-compose up -d

      - name: đợi container khởi động
        run: sleep 10

      - name: kiểm tra container
        run: docker ps

      - name: Kiểm tra ứng dụng
        run: |
          curl -f http://localhost:80 || exit 1

      - name: Dừng và dọn dẹp container
        run: docker-compose down
