name: Docker CI/CD cho AdvancedForum

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  #job1 Lint_code
  lint-code:
    runs-on: ubutu-latest

    steps:
      - name: Kéo mã nguồn về máy chủ
        uses: actions/checkout@v4
      - name: Thiết laapj pyrhon 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
      - name: Cài đặt các thư viện cần thiết
        run: pip install flake8

      - name: Quét mã nguồn bằng Flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  #job2 Build_and_test
  build-and-test:
    needs: lint-code
    runs-on: ubuntu-latest

    steps:
    - name: Kéo mã nguồn về máy chủ
      uses: actions/checkout@v4

    - name: Kiểm tra phiên bản Docker & Docker Compose
      run: |
        docker --version
        docker compose version # Đã sửa: dùng dấu cách và chữ 'version'

    - name: Build và khởi chạy hệ thống bằng Docker Compose
      # Đã sửa: Bỏ dấu gạch ngang
      run: docker compose up -d --scale web=3

    - name: Chờ hệ thống khởi động (10 giây)
      run: sleep 10

    - name: Kiểm tra trạng thái các Container
      # Đã sửa: Bỏ dấu gạch ngang
      run: docker compose ps

    - name: Kiểm tra kết nối Web (Ping thử Nginx)
      run: curl -f http://localhost:80 || exit 1

    - name: In ra Log của Flask App (để debug nếu cần)
      # Đã sửa: Bỏ dấu gạch ngang
      run: docker compose logs web

    - name: Dọn dẹp (Tắt container)
      # Đã sửa: Bỏ dấu gạch ngang
      run: docker compose down